### ISSUE TITLE
Remove angular from the parent window?

### ISSUE THREAD

**Issue by owennw** [ScottLogic/bitflux-openfin#315]
@WPFerg You had some ideas around this one?

**Comment by WPFerg** [comment]
I've had a proper look and try to remove Angular, and I think the current use of `$rootScope` and `$broadcast`/`$on` justifies leaving it in. Otherwise, we'd have to find a way to maintain an event emitter across windows. Angular does that for us and we wouldn't need to reinvent the wheel just to remove it.
